config/routes.rb
LargeProject::Application.routes.draw do
  resources :works

  get "static_pages/home"
  resources :artists

  resources :movements
  root 'static_pages#home'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true
  validates_format_of :born, with: /\d{4}-[0-1]\d-[0-3]\d/, message: "must have format: YYYY-MM-DD"
  validates :born, presence: true
  validates_format_of :died, with: /\d{4}-[0-1]\d-[0-3]\d/, message: "must have format: YYYY-MM-DD"
  validates :died, presence: true
  has_many :works

  def self.search(search)
    if search
      if !Movement.where('name LIKE ?', "%#{search}%").empty?
        where('name LIKE ? OR born LIKE ? OR died LIKE ? OR movement_id LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", Movement.where('name LIKE ?', "%#{search}%").first.id)
      else
        where('name LIKE ? OR born LIKE ? OR died LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
      end
    else
      all
    end
  end
end

app/models/movement.rb
class Movement < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  has_many :artists

  def self.search(search)
    if search
      where('name LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%")
    else
      all
    end
  end
end

app/models/work.rb
class Work < ActiveRecord::Base
  validates :name, presence: true
  validates :year_completed, presence: true
  validates_format_of :year_completed, with: /\d{4}/, message: "must have format: YYYY"
  validates :materials, presence: true

  def self.search(search)
    if search
      if !Artist.where('name LIKE ?', "%#{search}%").empty? && Movement.where('name LIKE ?', "%#{search}%").empty?
        where('name LIKE ? OR year_completed LIKE ? OR materials LIKE ? OR artist_id LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", Artist.where('name LIKE ?', "%#{search}%").first.id)
      else
        if Artist.where('name LIKE ?', "%#{search}%").empty? && !Movement.where('name LIKE ?', "%#{search}%").empty?
          where('name LIKE ? OR year_completed LIKE ? OR materials LIKE ? OR artist_id LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", Artist.where(movement_id: Movement.where('name LIKE ?', "%#{search}%").first.id).first.id)
        else
          where('name LIKE ? OR year_completed LIKE ? OR materials LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
        end
      end
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.search(params[:search])
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artist }
      else
        format.html { render action: 'new' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :movement_id, :born, :died)
    end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: [:show, :edit, :update, :destroy]

  # GET /movements
  # GET /movements.json
  def index
    @movements = Movement.search(params[:search])
  end

  # GET /movements/1
  # GET /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
  end

  # GET /movements/1/edit
  def edit
  end

  # POST /movements
  # POST /movements.json
  def create
    @movement = Movement.new(movement_params)

    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: 'Movement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @movement }
      else
        format.html { render action: 'new' }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1
  # PATCH/PUT /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to @movement, notice: 'Movement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movement_params
      params.require(:movement).permit(:name, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.search(params[:search])
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render action: 'show', status: :created, location: @work }
      else
        format.html { render action: 'new' }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :artist_id, :year_completed, :materials, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :movement_id %><br>
    <%= f.select :movement_id, Movement.all.collect {|p| [p.name, p.id] } %>
  </div>
  <div class="field">
    <%= f.label :born %><br>
    <%= f.text_field :born %>
  </div>
  <div class="field">
    <%= f.label :died %><br>
    <%= f.text_field :died %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing artists</h1>

<%= form_tag artists_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Movement</th>
      <th>Born</th>
      <th>Died</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= Movement.where(id: artist.movement_id).first.name %></td>
        <td><%= artist.born %></td>
        <td><%= artist.died %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Movement:</strong>
  <% movement = Movement.where(id: @artist.movement_id).first %>
  <%= link_to movement.name, movement %>
</p>

<p>
  <strong>Born:</strong>
  <%= @artist.born %>
</p>

<p>
  <strong>Died:</strong>
  <%= @artist.died %>
</p>

<center>
  <table>
    <thead>
      <tr>
        <th>Works</th>
      </tr>
    </thead>
  
    <tbody>
      <% Work.where(artist_id: @artist.id).each do |work| %>
        <tr>
          <td><%= link_to work.name, work %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</center>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Alex Milbrandt and Geoffrey Class
  </small>
  <nav>
    <ul>
      <li><a href="https://github.com/AlexMilbrandt/369-large-project">The Repository</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Large Project", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Movements",  movements_path %></li>
          <li><%= link_to "Artists",    artists_path %></li>
          <li><%= link_to "Works",      works_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LargeProject</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="inner_content">
	<div id="text">
          <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/movements/_form.html.erb
<%= form_for(@movement) do |f| %>
  <% if @movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% @movement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing movement</h1>

<%= render 'form' %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/index.html.erb
<h1>Listing movements</h1>

<%= form_tag movements_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movements.each do |movement| %>
      <tr>
        <td><%= movement.name %></td>
        <td><%= movement.description %></td>
        <td><%= link_to 'Show', movement %></td>
        <td><%= link_to 'Edit', edit_movement_path(movement) %></td>
        <td><%= link_to 'Destroy', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movement', new_movement_path %>

app/views/movements/new.html.erb
<h1>New movement</h1>

<%= render 'form' %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movement.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movement.description %>
</p>

<center>
  <table>
    <thead>
      <tr>
        <th>Artists</th>
      </tr>
    </thead>
  
    <tbody>
      <% Artist.where(movement_id: @movement.id).each do |artist| %>
        <tr>
          <td><%= link_to artist.name, artist %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</center>

<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>

app/views/static_pages/home.html.erb
<h1>Welcome to our App!</h1>
<p>
  <%= link_to "Movements", movements_path %>
</p>
<p>
  <%= link_to "Artists", artists_path %>
</p>
<%= link_to "Works", works_path %>

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br>
    <%= f.select :artist_id, Artist.all.collect {|p| [p.name, p.id] } %>
  </div>
  <div class="field">
    <%= f.label :year_completed %><br>
    <%= f.number_field :year_completed %>
  </div>
  <div class="field">
    <%= f.label :materials %><br>
    <%= f.text_area :materials %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<h1>Listing works</h1>

<%= form_tag works_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Movement</th>
      <th>Year completed</th>
      <th>Materials</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.name %></td>
        <td><%= Artist.where(id: work.artist_id).first.name %></td>
        <td><%= Movement.where(id: Artist.where(id: work.artist_id).first.id).first.name %></td>
        <td><%= work.year_completed %></td>
        <td><%= work.materials %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @work.name %>
</p>

<p>
  <strong>Artist:</strong>
  <% artist = Artist.where(id: @work.artist_id).first %>
  <%= link_to artist.name, artist %>
</p>

<p>
  <strong>Movement:</strong>
  <% movement = Movement.where(id: Artist.where(id: @work.artist_id).first.id).first %>
  <%= link_to movement.name, movement %>
</p>

<p>
  <strong>Year completed:</strong>
  <%= @work.year_completed %>
</p>

<p>
  <strong>Materials:</strong>
  <%= @work.materials %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @work.image_url %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>